name: Cron Build Redis

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Version verification
        run: |
          If ( -not ( Test-Path -Path .github\redis_latest_version.txt )) { 
            Add-Content -Path .github\redis_latest_version.txt -Value "" -NoNewline
          }
          $res = ConvertFrom-Json(Invoke-WebRequest -Headers @{'Authorization' = 'token ${{ secrets.ACTION_TOKEN }}'} -Uri "https://api.github.com/repos/redis/redis/releases/latest").Content
          If ( $res.tag_name -eq ( Get-Content .github\redis_latest_version.txt )) { 
            Write-Output "No new version"
            exit 1
          }
          $res.tag_name | Out-File -FilePath .github\redis_latest_version.txt -NoNewline -Encoding ascii
          $res.body -Replace '\(\#', '(https://github.com/redis/redis/pull/' | Set-Content .\redis_latest_body.txt
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$($res.tag_name)"
          Invoke-WebRequest -Uri https://github.com/redis/redis/archive/refs/tags/$($res.tag_name).tar.gz -OutFile redis-$($res.tag_name).tar.gz
          tar -xvf redis-$($res.tag_name).tar.gz
        shell: pwsh

      - name: Setup dotnet
        if: ${{ success() }}
        uses: actions/setup-dotnet@v3
      - run: |
          dotnet publish -c Release -r win-x64 --sc
        shell: pwsh

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: gcc make pkg-config mingw-w64-x86_64-python libopenssl openssl-devel
      - name: Build Redis
        if: ${{ success() }}
        run: |
          workspace=$(pwd)
          sed -i 's/__GNU_VISIBLE/1/' /d/a/_temp/msys64/usr/include/dlfcn.h
          cd redis-${{ env.RELEASE_VERSION }} && make -i PREFIX=$workspace/dist install BUILD_TLS=yes
          cp $workspace/README.md $workspace/start.bat /d/a/_temp/msys64/usr/bin/msys-2.0.dll /d/a/_temp/msys64/usr/bin/msys-crypto-3.dll /d/a/_temp/msys64/usr/bin/msys-ssl-3.dll redis.conf sentinel.conf $workspace/dist/bin/
          cd $workspace/dist/
          mv bin Redis-${{ env.RELEASE_VERSION }}-Windows-x64
          tar -cvzf $workspace/Redis-${{ env.RELEASE_VERSION }}-Windows-x64.tar.gz Redis-${{ env.RELEASE_VERSION }}-Windows-x64/*
          cp $workspace/publish/* Redis-${{ env.RELEASE_VERSION }}-Windows-x64/
          mv Redis-${{ env.RELEASE_VERSION }}-Windows-x64 Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service
          tar -cvzf $workspace/Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service.tar.gz Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service/*

      - name: Calculate the hash value
        if: ${{ success() }}
        run: |
          'Hashes' | Out-File -Append .\redis_latest_body.txt
          '=========' | Out-File -Append .\redis_latest_body.txt
          Get-FileHash .\Redis-${{ env.RELEASE_VERSION }}-Windows-x64.tar.gz | Format-List
          Get-FileHash .\Redis-${{ env.RELEASE_VERSION }}-Windows-x64.tar.gz | Format-List | Out-File -Append .\redis_latest_body.txt
          Get-FileHash .\Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service.tar.gz | Format-List
          Get-FileHash .\Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service.tar.gz | Format-List | Out-File -Append .\redis_latest_body.txt
        shell: pwsh

      - name: Add from workflow
        if: ${{ success() }}
        run: |
          "From workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | Out-File -Append .\redis_latest_body.txt
        shell: pwsh

      - name: Update
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github\redis_latest_version.txt
          git commit -m "update redis latest version"
          git push
        shell: pwsh

      - name: Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          name: Redis ${{ env.RELEASE_VERSION }} for Windows
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: redis_latest_body.txt
          files: |
            Redis-${{ env.RELEASE_VERSION }}-Windows-x64.tar.gz
            Redis-${{ env.RELEASE_VERSION }}-Windows-x64-with-Service.tar.gz
